### ISSUE TITLE
アドインが動作しません

### ISSUE THREAD

**Issue by RelaxTools** [fukushima-computer-system/outlook-check-recipients-addin#2]
こんにちは
入れてみたのですが、うまく動作しません。

現象
Desktop 版 アドインが表示されず、送信されてしまう。
Web版　以下のエラーになり送信されない。
![image](https://user-images.githubusercontent.com/10811735/141608862-05721dde-cd14-4724-ae49-b800e6c2c3c3.png)

アカウント(outlook.jpで追加）
wata***@outlook.jp

環境
Microsoft 365 Personal

Desktop版
Microsoft® Outlook® for Microsoft 365 MSO (バージョン 2111 ビルド 16.0.14701.20040) 64 ビット 

ブラウザ Chrome 
バージョン: 95.0.4638.69（Official Build） （64 ビット）

よろしくお願いいたします。

**Comment by fukushima-computer-system** [comment]
ご利用ありがとうございます。

ブラウザの設定で「サードパーティのCookieをブロックする」が有効になっている場合は、
本アドインはご利用いただけません。
アドインの個人用設定（文字の大きさ）を保持するためにブラウザのローカルストレージを使用しています。

**Comment by RelaxTools** [comment]
サードパーティのCookieを有効にしたら動作するようになりました。
ありがとうございます。
自力では解決できなかったので、注意事項に記述があればよいと思います。
ご検討ください。
